# numpy
* https://numpy.org/numpy-tutorials/
* numpy: Nemerical Python 과학적, 산업적 연산을 위한 패키지
* 다차원 배열, 행렬 연산에 주로 사용
* numpy는 python의 list와 비슷한 자료형
* 순서가 있는 자료형
* 파이썬의 list와의 차이는 자료형이 1가지만 들어간다.


# 차원
* 0차원 = 점 . 스칼라 a = 10 
* 1차원 = 선 --------  벡터, 배열, list, tuple [1,2,3,4]
  * 벡터는 방향을 가진 데이터
* 2차원 = 면, 가로, 세로, DB 테이블, Dataframe, matrix, 행렬
* 3차원 = 입체, 가로, 세로, 깊이, 정육면체
* 4차원 = 3차원 요소가 2개 이상
* 5차원 = 4차원 요소가 2개 이상

In [ ]:
# numpy는 외부 패키지이므로 설치 필요
# pip install numpy
# conda install numpy

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])

In [4]:
a

array([1, 2, 3, 4, 5])

In [5]:
s = 10

* 차원을 출력하는 메서드 .ndim, 
* 차원의 형태를 출력하는 메서드 .shape

In [6]:
s.ndim

AttributeError: 'int' object has no attribute 'ndim'

In [7]:
# ndarray는 벡터 이므로 1차원
a.ndim

1

In [8]:
# 방향이 없는 벡터
a.shape

(5,)

In [9]:
# 세로로 방향을 가진 열벡터
a2 = np.array([[1], [2], [3], [4], [5]])
a2.shape

(5, 1)

In [10]:
a2

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [11]:
a2.ndim

2

In [12]:
a3 = np.array([[1,2,3,4,5]])
a3

array([[1, 2, 3, 4, 5]])

In [13]:
a3.ndim

2

In [14]:
# 열벡터
a3.shape

(1, 5)

In [15]:
# 2차원 데이터
c = np.array([[1,2,3,4,5], [6,7,8,9,10]])
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [16]:
c.ndim

2

In [17]:
c.shape

(2, 5)

In [18]:
# 3차원 데이터
d = np.array([[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]],
             [[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]])
d

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

In [19]:
d.ndim

3

In [20]:
d.shape

(4, 2, 5)

In [22]:
# 4차원 데이터
e = np.array([[[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]],
             [[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]]])
e

array([[[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]],


       [[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]]])

In [23]:
e.ndim

4

In [24]:
e.shape

(2, 2, 2, 5)

In [33]:
# 5차원 데이터
f = np.array([[[[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]],
             [[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]]],
             [[[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]],
             [[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]]]])
f

array([[[[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]],


        [[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]]],



       [[[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]],


        [[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]]]])

In [34]:
f.ndim

5

In [35]:
f.shape

(2, 2, 2, 2, 5)

In [36]:
f[1] = f[1] + 5
f

array([[[[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]],


        [[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]]],



       [[[[ 6,  7,  8,  9, 10],
          [11, 12, 13, 14, 15]],

         [[ 6,  7,  8,  9, 10],
          [11, 12, 13, 14, 15]]],


        [[[ 6,  7,  8,  9, 10],
          [11, 12, 13, 14, 15]],

         [[ 6,  7,  8,  9, 10],
          [11, 12, 13, 14, 15]]]]])

In [45]:
f[1][0][1][1][3:] = f[1][0][1][1][3:] * 2
f

array([[[[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]],


        [[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]]],



       [[[[ 6,  7,  8,  9, 10],
          [11, 12, 13, 14, 15]],

         [[ 6,  7,  8,  9, 10],
          [11, 12, 13, 28, 30]]],


        [[[ 6,  7,  8,  9, 10],
          [11, 12, 13, 14, 15]],

         [[ 6,  7,  8,  9, 10],
          [11, 12, 13, 14, 15]]]]])

# 넘파이를 사용하는 이유
* 행렬 연산이 쉽고 빠르기 때문

In [46]:
# 스칼라 연산
a = 10
b =  5
scalar = a + b
print(scalar)

15


In [47]:
scalar + 10

25

In [50]:
# 1차원 데이터 벡터의 연산
b1 = [1,2,3,4,5]
# 리스의 요소에 10을 곱한 후 다시 리스트로 만드세요.
result = []
for num in b1:
    result.append(num*10)
result

[10, 20, 30, 40, 50]

In [53]:
result2 = [num * 10 for num in b1]
result2

[10, 20, 30, 40, 50]

In [49]:
# 2차원 데이터 계산 * 10 하기
second = np.array([[1,2,3], [1,2,3]])
print(second, second.ndim, second.shape)

[[1 2 3]
 [1 2 3]] 2 (2, 3)


In [50]:
result = []
for num in second:
    mid_result = []
    for number in num:
        mid_result.append(number * 10)
    result.append(mid_result)
result = np.array(result)

In [51]:
result.ndim

2

In [52]:
result.shape

(2, 3)

In [53]:
result

array([[10, 20, 30],
       [10, 20, 30]])

In [55]:
# 3차원 데이터의 요소에 10 곱하기
third = np.array([[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]])
print(third, third.ndim, third.shape)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]] 3 (2, 2, 3)


In [56]:
result = []
for num1 in third:
    num1_result = []
    for num2 in num1:
        num2_result = []
        for num3 in num2:
            num2_result.append(num3 * 10)
        num1_result.append(num2_result)
    result.append(num1_result)
result = np.array(result)

In [57]:
result.ndim

3

In [58]:
result

array([[[10, 20, 30],
        [10, 20, 30]],

       [[10, 20, 30],
        [10, 20, 30]]])

In [81]:
result.shape

(2, 2, 3)

In [64]:
# 4차원 데이터 요소에 10 곱하기
forth = np.array([[[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]],
                 [[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]]])
print(forth.ndim, forth.shape)

4 (2, 2, 2, 3)


In [65]:
forth[0] = forth[0] * 10
forth[1] = forth[1] / 10
forth

array([[[[10, 20, 30],
         [10, 20, 30]],

        [[10, 20, 30],
         [10, 20, 30]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0]]]])

In [66]:
# 5차원 데이터 요소에 10 곱하기
fifth = np.array([[[[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]],
                 [[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]]],
                 [[[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]],
                 [[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]]]])
print(fifth.ndim, fifth.shape)

5 (2, 2, 2, 2, 3)


In [67]:
fifth * 10

array([[[[[10, 20, 30],
          [10, 20, 30]],

         [[10, 20, 30],
          [10, 20, 30]]],


        [[[10, 20, 30],
          [10, 20, 30]],

         [[10, 20, 30],
          [10, 20, 30]]]],



       [[[[10, 20, 30],
          [10, 20, 30]],

         [[10, 20, 30],
          [10, 20, 30]]],


        [[[10, 20, 30],
          [10, 20, 30]],

         [[10, 20, 30],
          [10, 20, 30]]]]])

# numpy에서 자주 사용하는 메서드
* .ndim: 몇 차원인지 보는 것
* .shape: 몇차원, 몇행, 몇열로 되어 있는지 구조 확인
* .size: 배열 안에 있는 요소의 총 개수가 몇 개인지
* .dtype: 데이터 타입이 무엇인지

In [69]:
fifth

array([[[[[1, 2, 3],
          [1, 2, 3]],

         [[1, 2, 3],
          [1, 2, 3]]],


        [[[1, 2, 3],
          [1, 2, 3]],

         [[1, 2, 3],
          [1, 2, 3]]]],



       [[[[1, 2, 3],
          [1, 2, 3]],

         [[1, 2, 3],
          [1, 2, 3]]],


        [[[1, 2, 3],
          [1, 2, 3]],

         [[1, 2, 3],
          [1, 2, 3]]]]])

In [68]:
len(fifth)

2

In [70]:
fifth.ndim

5

In [71]:
fifth.shape

(2, 2, 2, 2, 3)

In [72]:
fifth.size

48

In [73]:
fifth.dtype

dtype('int64')

In [91]:
fifth2 = fifth / 2
print(fifth2)
print(fifth2.dtype)

[[[[[0.5 1.  1.5]
    [0.5 1.  1.5]]

   [[0.5 1.  1.5]
    [0.5 1.  1.5]]]


  [[[0.5 1.  1.5]
    [0.5 1.  1.5]]

   [[0.5 1.  1.5]
    [0.5 1.  1.5]]]]



 [[[[0.5 1.  1.5]
    [0.5 1.  1.5]]

   [[0.5 1.  1.5]
    [0.5 1.  1.5]]]


  [[[0.5 1.  1.5]
    [0.5 1.  1.5]]

   [[0.5 1.  1.5]
    [0.5 1.  1.5]]]]]
float64


# ndarray 만들기
* numpy의 기본 자료형 ndarray
* np.array(리스트/튜플)
* 자료형은 반드시 1가지만 넣는다.

In [94]:
print(*[1,2,3,4,5])

1 2 3 4 5


In [75]:
# e = np.array([1,2,3,4,5])
e = np.array([1,2,3,4,5])
e

array([1, 2, 3, 4, 5])

In [76]:
e2 = np.array((1, 2, 3.14, 4, 5))
print(e2)
e2.dtype


[1.   2.   3.14 4.   5.  ]


dtype('float64')

In [80]:
e3 = np.array((True, 1, 2, 3.14, "4", 5))
print(e3)
print(e3.dtype)
print(e3[2].dtype)

['True' '1' '2' '3.14' '4' '5']
<U32
<U1


* np.arange(시작, 끝, step)

In [104]:
a = np.arange(1, 11, 2)
a

array([1, 3, 5, 7, 9])

In [105]:
a2 = np.arange(11, 1, -3)
a2

array([11,  8,  5,  2])

In [83]:
# 1-100까지 있는 array
a3 = np.arange(1, 101)
a3

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

* .reshape(행, 열)

In [84]:
# .reshape(행, 열) 벡터를 원하는 크기의 matrix 또는 다차원 배열로 변환
print(a3.ndim)
print(a3.shape)
a4 = a3.reshape(20, 5)
print(a4.ndim)
print(a4.shape)

1
(100,)
2
(20, 5)


In [85]:
a4

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])

In [88]:
a4 = a3.reshape(5, 2, 2, 5)
print(a4.ndim)
print(a4.shape)

4
(5, 2, 2, 5)


In [89]:
a4

array([[[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10]],

        [[ 11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20]]],


       [[[ 21,  22,  23,  24,  25],
         [ 26,  27,  28,  29,  30]],

        [[ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40]]],


       [[[ 41,  42,  43,  44,  45],
         [ 46,  47,  48,  49,  50]],

        [[ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60]]],


       [[[ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70]],

        [[ 71,  72,  73,  74,  75],
         [ 76,  77,  78,  79,  80]]],


       [[[ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90]],

        [[ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]]]])

In [112]:
a5 = a3.reshape(5 ,4, 5)
a5

array([[[  1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20]],

       [[ 21,  22,  23,  24,  25],
        [ 26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40]],

       [[ 41,  42,  43,  44,  45],
        [ 46,  47,  48,  49,  50],
        [ 51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60]],

       [[ 61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75],
        [ 76,  77,  78,  79,  80]],

       [[ 81,  82,  83,  84,  85],
        [ 86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100]]])

In [115]:
a3

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [119]:
a6 = a3.reshape(4, 25)
print(a6.ndim)
print(a6.shape)
a6

2
(4, 25)


array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
         89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

* flatten()

In [91]:
# flatten() : 다차원 배열을 1차원으로 펼쳐줌
print(a4)
a4.flatten()

[[[[  1   2   3   4   5]
   [  6   7   8   9  10]]

  [[ 11  12  13  14  15]
   [ 16  17  18  19  20]]]


 [[[ 21  22  23  24  25]
   [ 26  27  28  29  30]]

  [[ 31  32  33  34  35]
   [ 36  37  38  39  40]]]


 [[[ 41  42  43  44  45]
   [ 46  47  48  49  50]]

  [[ 51  52  53  54  55]
   [ 56  57  58  59  60]]]


 [[[ 61  62  63  64  65]
   [ 66  67  68  69  70]]

  [[ 71  72  73  74  75]
   [ 76  77  78  79  80]]]


 [[[ 81  82  83  84  85]
   [ 86  87  88  89  90]]

  [[ 91  92  93  94  95]
   [ 96  97  98  99 100]]]]


array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [96]:
a7 = np.arange(24)
a7 = a7.reshape(3,2,2,2)
a7

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [97]:
a7.ndim

4

In [98]:
a7.shape

(3, 2, 2, 2)

In [99]:
a72 = a7.flatten()
a72

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [100]:
a73 = a72.reshape(3,2,2,2)
a73

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [101]:
a73.ndim

4

In [102]:
a73.shape

(3, 2, 2, 2)

In [103]:
# np.flip() 행렬의 순서를 뒤집을 때
print(a73)
np.flip(a73)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]


 [[[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]]


array([[[[23, 22],
         [21, 20]],

        [[19, 18],
         [17, 16]]],


       [[[15, 14],
         [13, 12]],

        [[11, 10],
         [ 9,  8]]],


       [[[ 7,  6],
         [ 5,  4]],

        [[ 3,  2],
         [ 1,  0]]]])

In [104]:
a73.shape

(3, 2, 2, 2)

In [136]:
a73[::-1]

array([[[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]]])

* np.linspace(시작, 끝, 구간 수)

In [137]:
# np.linspace(시작, 끝, 구간 수): 정해진 숫자 범위 안에서 균등하게 구간을 나눌 때
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [139]:
np.linspace(1, 10, 33)

array([ 1.     ,  1.28125,  1.5625 ,  1.84375,  2.125  ,  2.40625,
        2.6875 ,  2.96875,  3.25   ,  3.53125,  3.8125 ,  4.09375,
        4.375  ,  4.65625,  4.9375 ,  5.21875,  5.5    ,  5.78125,
        6.0625 ,  6.34375,  6.625  ,  6.90625,  7.1875 ,  7.46875,
        7.75   ,  8.03125,  8.3125 ,  8.59375,  8.875  ,  9.15625,
        9.4375 ,  9.71875, 10.     ])

In [140]:
np.linspace(1, 10, 539)

array([ 1.        ,  1.01672862,  1.03345725,  1.05018587,  1.0669145 ,
        1.08364312,  1.10037175,  1.11710037,  1.133829  ,  1.15055762,
        1.16728625,  1.18401487,  1.20074349,  1.21747212,  1.23420074,
        1.25092937,  1.26765799,  1.28438662,  1.30111524,  1.31784387,
        1.33457249,  1.35130112,  1.36802974,  1.38475836,  1.40148699,
        1.41821561,  1.43494424,  1.45167286,  1.46840149,  1.48513011,
        1.50185874,  1.51858736,  1.53531599,  1.55204461,  1.56877323,
        1.58550186,  1.60223048,  1.61895911,  1.63568773,  1.65241636,
        1.66914498,  1.68587361,  1.70260223,  1.71933086,  1.73605948,
        1.7527881 ,  1.76951673,  1.78624535,  1.80297398,  1.8197026 ,
        1.83643123,  1.85315985,  1.86988848,  1.8866171 ,  1.90334572,
        1.92007435,  1.93680297,  1.9535316 ,  1.97026022,  1.98698885,
        2.00371747,  2.0204461 ,  2.03717472,  2.05390335,  2.07063197,
        2.08736059,  2.10408922,  2.12081784,  2.13754647,  2.15

In [142]:
np.linspace(0, 1, 13)

array([0.        , 0.08333333, 0.16666667, 0.25      , 0.33333333,
       0.41666667, 0.5       , 0.58333333, 0.66666667, 0.75      ,
       0.83333333, 0.91666667, 1.        ])

In [105]:
# 정렬, .sort(), sorted()
f = np.array([5 , 7 , 11, 1 , 3, 2, 54, 0, 0.5, 68])
f

array([ 5. ,  7. , 11. ,  1. ,  3. ,  2. , 54. ,  0. ,  0.5, 68. ])

In [106]:
print(sorted(f))
f

[np.float64(0.0), np.float64(0.5), np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(5.0), np.float64(7.0), np.float64(11.0), np.float64(54.0), np.float64(68.0)]


array([ 5. ,  7. , 11. ,  1. ,  3. ,  2. , 54. ,  0. ,  0.5, 68. ])

In [107]:
print(sorted(f, reverse=True))
f

[np.float64(68.0), np.float64(54.0), np.float64(11.0), np.float64(7.0), np.float64(5.0), np.float64(3.0), np.float64(2.0), np.float64(1.0), np.float64(0.5), np.float64(0.0)]


array([ 5. ,  7. , 11. ,  1. ,  3. ,  2. , 54. ,  0. ,  0.5, 68. ])

* np.sort()

In [109]:
arr = np.array([
    [[5,2,8],
    [1,6,7]],
    
    [[4,9,3],
    [0,2,1]]
])
print(arr)
print(arr.ndim)
print(arr.shape)

[[[5 2 8]
  [1 6 7]]

 [[4 9 3]
  [0 2 1]]]
3
(2, 2, 3)


In [110]:
# axis=-1 가장 안쪽 차원 1차원 배열을 정렬
# np.sort() 함수의 axis 기본값은 -1
print(arr)
np.sort(arr)

[[[5 2 8]
  [1 6 7]]

 [[4 9 3]
  [0 2 1]]]


array([[[2, 5, 8],
        [1, 6, 7]],

       [[3, 4, 9],
        [0, 1, 2]]])

In [111]:
# axis=1 2차원 배열에서 각 열을 정렬
# np.sort() 함수의 axis 기본값은 -1
print(arr)
np.sort(arr, axis=1)

[[[5 2 8]
  [1 6 7]]

 [[4 9 3]
  [0 2 1]]]


array([[[1, 2, 7],
        [5, 6, 8]],

       [[0, 2, 1],
        [4, 9, 3]]])

In [113]:
# axis=0 
# np.sort() 함수의 axis 기본값은 -1
print(arr)
np.sort(arr, axis=0)

[[[5 2 8]
  [1 6 7]]

 [[4 9 3]
  [0 2 1]]]


array([[[4, 2, 3],
        [0, 2, 1]],

       [[5, 9, 8],
        [1, 6, 7]]])

* argsort()

In [164]:
# argsort() 자료중 값이 작은 것에서 큰 순으로 원래 인덱스 출력
g = np.array([5, 0.5, -7, 42, 10, 0])
print(g)

[ 5.   0.5 -7.  42.  10.   0. ]


In [ ]:
# 2, 5, 1, 0, 4, 3

In [166]:
s = g.argsort()
s

array([2, 5, 1, 0, 4, 3])

In [169]:
g[s][::-1]

array([42. , 10. ,  5. ,  0.5,  0. , -7. ])

* np.where(조건, 참, 거짓) 3항 연산

In [114]:
num = np.arange(1, 11)
num

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [115]:
np.where(num % 2==0, "짝수", "홀수")

array(['홀수', '짝수', '홀수', '짝수', '홀수', '짝수', '홀수', '짝수', '홀수', '짝수'],
      dtype='<U2')

In [116]:
result = []
for i in num:
    if i % 2 ==0:
        result.append('짝수')
    else:
        result.append("홀수")
result

['홀수', '짝수', '홀수', '짝수', '홀수', '짝수', '홀수', '짝수', '홀수', '짝수']

# 배열 합치기 np.concatenate()

In [118]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
print(a, a.shape, a.ndim)
print(b, b.shape, b.ndim)

[[1 2]
 [3 4]] (2, 2) 2
[[5 6]
 [7 8]] (2, 2) 2


* np.concatenate((a,b)) 
* 합치는 기본 방향은 axis=0 행이 늘어남, 아래로 붙음
* axis=1 열이 늘어남, 옆으로 붙음

In [119]:
# axis=0 아래로 늘어나면서 합쳐짐
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [120]:
np.concatenate((a,b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# 합치는 방향의 모양이 일치하지 않으면 합치기 X

In [124]:
c = np.array([5,6])
print(c, c.ndim, c.shape)

[5 6] 1 (2,)


In [125]:
# 차원이 맞지 않아서 합쳐지지 않음
np.concatenate((a, c))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [126]:
d = np.array([[7,8,9]])
print(d, d.ndim, d.shape)

[[7 8 9]] 2 (1, 3)


In [127]:
a

array([[1, 2],
       [3, 4]])

In [129]:
d

array([[7, 8, 9]])

In [131]:
np.concatenate((a,d), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [2]:
e = np.array([[1,2,3],[4,5,6]])
print(e, e.ndim, e.shape)

[[1 2 3]
 [4 5 6]] 2 (2, 3)


In [134]:
np.concatenate((d,e))

array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [135]:
np.concatenate((d,e), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 1 and the array at index 1 has size 2

In [137]:
f = np.array([[1,2], [3,4], [5,6]])
print(f, f.ndim, f.shape)

[[1 2]
 [3 4]
 [5 6]] 2 (3, 2)


In [138]:
e

array([[1, 2, 3],
       [4, 5, 6]])

In [139]:
f

array([[1, 2],
       [3, 4],
       [5, 6]])

In [144]:
np.concatenate((e, f), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

In [147]:
# 전치행렬: 행과 열을 바꿈
print(f)
print(f.shape)
print(f.T)
print(f.T.shape)


[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[1 3 5]
 [2 4 6]]
(2, 3)


In [149]:
np.concatenate((e, f.T), axis=1 )

array([[1, 2, 3, 1, 3, 5],
       [4, 5, 6, 2, 4, 6]])

# 전치 행렬 만들기
* .T
* .transpose()

In [150]:
e

array([[1, 2, 3],
       [4, 5, 6]])

In [151]:
e.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [3]:
e.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

# 브로드 캐스팅
* 벡터와 스칼라, 혹은 매트릭스와 벡터를 연산할 때 자동으로 행렬 크기를 맞춰 주는 것

In [5]:
a = np.arange(1, 16).reshape(3,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [6]:
a + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [159]:
print(a, a.ndim, a.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]] 2 (3, 5)


In [158]:
b = np.array([10, 20, 30, 40, 50])
print(b, b.ndim, b.shape)

[10 20 30 40 50] 1 (5,)


In [160]:
a + b

array([[11, 22, 33, 44, 55],
       [16, 27, 38, 49, 60],
       [21, 32, 43, 54, 65]])